### ISSUE TITLE
huawei_location: ^6.14.2+300 D8: java.lang.NullPointerException

### ISSUE THREAD

**Issue by markjoseultra** [HMS-Core/hms-flutter-plugin#401]
Hi Team, I am using flutter to develop an application for huawei, I need to use huawei_location and I followed the instructions here https://developer.huawei.com/consumer/en/codelab/HMSPreparation/index.html#6 gradle 7.1

everything works fine until I add the huawei_location: ^6.14.2+300, once I run the app this error is returned

![image](https://github.com/user-attachments/assets/98e19ee5-a1eb-4e63-bcfb-5fd389e5cc02)

If I remove huawei_location: ^6.14.2+300 the app runs but I can't get the device coordinates, thanks in advance.

**Comment by github785248126** [comment]
Have you solved it yet? I have also encountered this problem

**Comment by github785248126** [comment]
After switching to version 6.12.0+302, the problem was resolved

**Comment by Ellynnn** [comment]
I'm facing the same problem too. Even after switching to version 6.12.0+302, I'm still facing the same problem. Does anyone know what else could be the cause?
